### ISSUE TITLE
Unable to use "first char" lexer optimizations

### ISSUE THREAD

**Issue by danielcurran** [bd82/regexp-to-ast#131]
See error below:

`Error: Unable to use "first char" lexer optimizations:

        Failed parsing: < /((?<!\\)'''(.|\n)*?(?<!\\)''')|((?<!\\)"""(.|\n)*?(?<!\\)""")|((?<!\\)".*?(?<!\\)")|((?<!\\)'.*?(?<!\\)')/y >
        Using the regexp-to-ast library version: 0.5.0
        Please open an issue at: https://github.com/bd82/regexp-to-ast/issues`

**Comment by bd82** [comment]
Hello @danielcurran 

This repo is no longer maintained.
The code moved to https://github.com/Chevrotain/chevrotain/tree/master/packages/regexp-to-ast
You should try to reproduce with the most recent version of Chevrotain and open an issue
on the Chevrotain repo.

If this reproduces it would also be helpful to minimize the reproducing regexp if possible...
