### ISSUE TITLE
Failed parsing: < /{/ >

### ISSUE THREAD

**Issue by brainkim** [bd82/regexp-to-ast#5]
```
Error: Unable to use "first char" lexer optimizations:

        Failed parsing: < /{/ >
        Using the regexp-to-ast library version: undefined
        Please open an issue at: https://github.com/bd82/regexp-to-ast/issues
```
I was told to open an issue here so here I am :)

**Comment by bd82** [comment]
Thanks.

As a workaround use the string literal "{" as the pattern in Chevrotain.
Escaping may also work around it
```javascript
/\{/
```

The curly braces are used for quantifier specifier.
```javascript
/a{2}/ // matches "aa"
/a{1,4} // matches "a" "aa" "aaa" "aaaa"
```

but apparently it can also be used in a literal form without escaping
```javascript
/a{/ // matches "a{"
```
