### ISSUE TITLE
Failed parsing /[0-9]+[a-z]{0,3}/

### ISSUE THREAD

**Issue by danielo515** [bd82/regexp-to-ast#6]
This is all the error I got:

```
        Failed parsing: < /[0-9]+[a-z]{0,3}/ >
        Using the regexp-to-ast library version: 0.2.2
        Please open an issue at: https://github.com/bd82/regexp-to-ast/issues
```

Hope you can fix it because I'm trying to use them as part of Chevrotain

**Comment by bd82** [comment]
Hello. 

Thanks for reporting this.
Note that this is a warning that Chevrotain cannot  optimize your lexer, but it d**oes not mean
that it won't work correctly.**

So this does not impact the correctness of whatever you are building.
Only the performance.

**Comment by bd82** [comment]
I can't release a new version yet because of auth issues with npmjs.com
I will try again tomorrow or the next day.

**Comment by bd82** [comment]
http://sap.github.io/chevrotain/docs/changes/CHANGELOG.html#_3-4-0-6-6-2018

Chevrotain 3.4.0 now uses regexp-to-ast 0.2.4 with the required fixes
